obj = open("data.txt","a")
name=input("Enter your name:")
email=input("Enter your email: ")
address=input("ENTER YOUR ADDRESS:")
obj.write(name)
obj.write("\n")
obj.write(email)
obj.write("\n")
obj.write(address)
obj.write("\n")
obj.close()